### ISSUE TITLE
Broken for 20w16a

### ISSUE THREAD

**Issue by evoandroidevo** [gbl/WorldTime#3]
[Info: 2020-04-16 03:30:33.6115923: GameCallbacks.cpp(158)] Game/FabricLoader (main) Info Loading for game Minecraft 20w16a
[Info: 2020-04-16 03:30:34.9464503: GameCallbacks.cpp(158)] Game/Fabric|Loader (main) Fatal A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: worldtime requires {fabric @ [*]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:169)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:602)
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:179)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:169)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:167)
	... 5 more

**Comment by gbl** [comment]
Could not find required mod: worldtime requires {fabric @ [*]} - you need the Fabric API as well, not just the loader.
